{
 "title": "Asus Router",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ProductID",
    "query": {
     "query": "label_values(asus_router_cpu_total,product_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Speed",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(asus_router_netdev_internet_receive_bytes_total{product_id=\"$ProductID\"}[10s]) * 8 / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(asus_router_netdev_internet_transmit_bytes_total{product_id=\"$ProductID\"}[10s]) * 8 / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(asus_router_cpu_usage_percent[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_link_internet_status{product_id=\"$ProductID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_cpu_temperature_celsius{product_id=\"$ProductID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_sw_mode{product_id=\"$ProductID\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active WAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_active{product_id=\"$ProductID\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(asus_router_memory_used_bytes{product_id=\"$ProductID\"} / asus_router_memory_total_bytes{product_id=\"$ProductID\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_uptime_seconds{product_id=\"$ProductID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Until Next Reboot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_reboot_schedule_second_until_next{product_id=\"$ProductID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Dual WAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_dualwan_enabled{product_id=\"$ProductID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary WAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_online{product_id=\"$ProductID\",unit=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary WAN Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_status{product_id=\"$ProductID\",unit=\"0\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary WAN Cable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_auxstate{product_id=\"$ProductID\",unit=\"0\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary WAN State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_state{product_id=\"$ProductID\",unit=\"0\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary WAN Substate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_substate{product_id=\"$ProductID\",unit=\"0\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dual WAN Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_dualwan_mode{product_id=\"$ProductID\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary WAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_online{product_id=\"$ProductID\",unit=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary WAN Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_status{product_id=\"$ProductID\",unit=\"1\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary WAN Cable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_auxstate{product_id=\"$ProductID\",unit=\"1\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary WAN State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_state{product_id=\"$ProductID\",unit=\"1\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary WAN Substate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "asus_router_wan_connection_substate{product_id=\"$ProductID\",unit=\"1\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cummulative Statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Data Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(asus_router_netdev_internet_receive_bytes_total{product_id=\"$ProductID\"}[1h] offset -1h)",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "increase(asus_router_netdev_internet_transmit_bytes_total{product_id=\"$ProductID\"}[1h] offset -1h)",
     "legendFormat": "Uploaded"
    }
   ]
  },
  {
   "title": "Data Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(asus_router_netdev_internet_receive_bytes_total{product_id=\"$ProductID\"}[1d] offset -1d )",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "increase(asus_router_netdev_internet_transmit_bytes_total{product_id=\"$ProductID\"}[1d] offset -1d)",
     "legendFormat": "Uploaded"
    }
   ]
  },
  { "title": "Hadware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(asus_router_cpu_usage_total{product_id=\"$ProductID\"}[1m]) / irate(asus_router_cpu_total{product_id=\"$ProductID\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(asus_router_memory_used_bytes{product_id=\"$ProductID\"}[30s])",
     "legendFormat": "Used"
    },
    {
     "expr": "asus_router_memory_total_bytes{product_id=\"$ProductID\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Temperature (℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(asus_router_cpu_temperature_celsius{product_id=\"$ProductID\"}[15s])",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Internet",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(asus_router_netdev_internet_receive_bytes_total{product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(asus_router_netdev_internet_transmit_bytes_total{product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "LAN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(asus_router_netdev_wired_receive_bytes_total{product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(asus_router_netdev_wired_transmit_bytes_total{product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Wireless (2.4GHz)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(asus_router_netdev_wireless_receive_bytes_total{interface_id=\"0\", product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(asus_router_netdev_wireless_transmit_bytes_total{interface_id=\"0\",product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Wireless (5GHz)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(asus_router_netdev_wireless_receive_bytes_total{interface_id=\"1\", product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Receive"
    },
    {
     "expr": "irate(asus_router_netdev_wireless_transmit_bytes_total{interface_id=\"1\", product_id=\"$ProductID\"}[5s]) * 8",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}